import Foundation

/// Re-launches this same binary as a detached recorder.
///
/// The caller cannot be relied on to background it: a shell's process group is
/// killed when a tool times out, and `&` gives no synchronous answer to "is
/// capture actually live yet?" — which is exactly what a caller needs before it
/// presses play on the thing it wants recorded.
enum DetachedLauncher {
    enum LaunchError: Error, CustomStringConvertible {
        case spawnFailed(Int32)
        case neverStarted(String)

        var description: String {
            switch self {
            case .spawnFailed(let code):
                return "could not spawn the recorder: \(String(cString: strerror(code)))"
            case .neverStarted(let detail):
                return "the recorder did not start: \(detail)"
            }
        }
    }

    /// Spawns `executable arguments…` in its own session, detached from this
    /// process group and terminal, with stdout and stderr appended to `logURL`.
    static func spawn(arguments: [String], logURL: URL) throws -> pid_t {
        let executable = Bundle.main.executablePath ?? CommandLine.arguments[0]
        let argv = [executable] + arguments

        var pointers: [UnsafeMutablePointer<CChar>?] = argv.map { $0.withCString(strdup) } + [nil]
        defer { pointers.forEach { free($0) } }

        var actions: posix_spawn_file_actions_t?
        posix_spawn_file_actions_init(&actions)
        defer { posix_spawn_file_actions_destroy(&actions) }
        posix_spawn_file_actions_addopen(&actions, 0, "/dev/null", O_RDONLY, 0)
        posix_spawn_file_actions_addopen(
            &actions, 1, logURL.path, O_WRONLY | O_CREAT | O_APPEND, 0o644)
        posix_spawn_file_actions_adddup2(&actions, 1, 2)

        var attributes: posix_spawnattr_t?
        posix_spawnattr_init(&attributes)
        defer { posix_spawnattr_destroy(&attributes) }
        // A new session: no controlling terminal, immune to the caller's process
        // group being torn down and to the SIGHUP that follows a closed shell.
        posix_spawnattr_setflags(&attributes, Int16(POSIX_SPAWN_SETSID))

        var pid: pid_t = 0
        // The environment is passed through deliberately: the summariser shells
        // out to `zsh -lc which claude`, and the claude CLI needs HOME and PATH.
        let result = posix_spawn(&pid, executable, &actions, &attributes, &pointers, environ)
        guard result == 0 else { throw LaunchError.spawnFailed(result) }
        return pid
    }

    /// Waits for the spawned child to report that capture is live. Matching on
    /// the session id (generated by the parent) rather than on "some recording
    /// exists" is what makes this immune to a leftover state document.
    static func awaitStart(
        sessionID: String, pid: pid_t, timeout: TimeInterval = 20
    ) throws -> RecordingState {
        let deadline = Date().addingTimeInterval(timeout)
        while Date() < deadline {
            if let found = RecordingRegistry.read(.cli), found.state.sessionID == sessionID {
                switch found.state.phase {
                case .recording, .processing, .done:
                    return found.state
                case .failed, .cancelled:
                    throw LaunchError.neverStarted(found.state.error ?? "\(found.state.phase)")
                case .starting:
                    break
                }
            }
            // The child dying before it ever wrote a state document (a crash on
            // launch, a missing dylib) would otherwise hang here until timeout.
            var status: Int32 = 0
            if waitpid(pid, &status, WNOHANG) == pid {
                throw LaunchError.neverStarted(
                    "it exited with status \(status >> 8); see \(RecordingRegistry.logURL.path)")
            }
            usleep(100_000)
        }
        throw LaunchError.neverStarted("timed out after \(Int(timeout))s")
    }
}

/// The parent half of `dikta record`: spawn, wait for "recording", print where
/// it went, and get out of the way.
func runDetachedRecord(options: RecordingSessionOptions, rawArguments: [String]) -> Int32 {
    let sessionID = UUID().uuidString
    let arguments = ["record"] + rawArguments + ["--foreground", "--session-id", sessionID]
    // Before the spawn, not inside the child: the file action that opens the
    // log lives in the parent's call and fails the whole spawn without it.
    RecordingRegistry.ensureDirectory()

    do {
        let pid = try DetachedLauncher.spawn(
            arguments: arguments, logURL: RecordingRegistry.logURL)
        let state = try DetachedLauncher.awaitStart(sessionID: sessionID, pid: pid)
        let directory = state.sessionDirectory ?? ""
        if options.json {
            printJSON([
                "sessionID": sessionID,
                "pid": Int(pid),
                "sessionDirectory": directory,
                "displayID": state.displayID.map(Int.init) as Any,
                "displayIndex": state.displayIndex as Any,
            ])
        } else {
            note("record", "recording (pid \(pid)) — stop it with `dikta stop`")
            print(directory)
        }
        return 0
    } catch {
        note("record", "\(error)")
        return 1
    }
}
